apiVersion: v1
kind: Pod
metadata:
  name: score-checker-api-pod
  labels:
    app: score-checker-api-pod
spec:
  containers:
    - name: score-checker-container
      image: score-checker-api:1
      ports:
        - containerPort: 8080