apiVersion: v1
kind: Service
metadata:
  name: score-checker-api-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      #porta do serviço
      port: 8081
      #porta que ta exposta no pod
      targetPort: 8080
      #porta acessivel de fora do cluster
      nodePort: 30000
  selector:
    app: score-checker-api-pod